version: '3.9'

services:
  mongo:
    image: mongo:7.0
    container_name: auth-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: authDB
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    container_name: onlineide-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    
  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    environment:
      - MONGO_URI=mongodb://admin:admin123@mongo:27017
      - JWT_SECRET_KEY=thisisaverysecuresecretkey
      - JWT_REFRESH_SECRET_KEY=thisisaverysecuresecretkey
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
      - rabbitmq

  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/
      - CLOUDINARY_CLOUD_NAME=yourcloudinarycloudname
      - CLOUDINARY_API_KEY=yourcloudinaryapikey
      - CLOUDINARY_API_SECRET=yourcloudinaryapisecret
    depends_on:
      - mongo
      - redis
      - rabbitmq

  email-service:
    build: ./email-service
    container_name: email-service
    restart: always
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - BREVO_API_KEY=writeyourapikeyhere
      - SMTP_HOST=smtp-relay.sendinblue.com
      - SMTP_PORT=587
      - SMTP_EMAIL=writeYourEmailHere
      - BASE_URL=http://localhost:3000
    depends_on:
      - rabbitmq

  project-service:
    build: ./project-service
    container_name: project-service
    restart: always
    volumes:
      - ./project-service/src:/app/src
      - ./project-service/dist:/app/dist
      - ./code:/app/src/code
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - PORT=3005
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/
  
  docker-service:
    build: ./docker-service
    container_name: docker-service
    restart: always
    volumes:
      - ./docker-service/src:/app/src
      - ./docker-service/dist:/app/dist
      - ./code:/app/src/code
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq

  websocket-service:
    build: ./websocket
    container_name: websocket-service
    restart: always
    volumes:
      - ./websocket/src:/app/src
      - ./websocket/dist:/app/dist
      - ./code:/app/src/code
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
        - auth-service
        - user-service
volumes:
  mongo-data:
  redis_data:
